### ISSUE TITLE
Failing to execute and giving : no address found in preferences

### ISSUE THREAD

**Issue by linux-modder** [pithos/pithos#124]
on fedora 20 with pithos from repos and no dice

**Comment by skamansam** [comment]
I get the following errors. I just start it and try to open preferences:
sam$ pithos -vv
INFO - pithos:do_activate:1090 - Pithos 1.0.1
INFO - pithos:set_player_volume:922 - 0.783
INFO - plugin:enable:35 - Enabling module screensaver_pause
INFO - plugin:enable:35 - Enabling module notification_icon
INFO - plugin:enable:35 - Enabling module mediakeys
INFO - mediakeys:bind_dbus:36 - Bound media keys with DBUS
INFO - plugin:enable:35 - Enabling module scrobble
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 1084, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 1091, in do_activate
    self.window = NewPithosWindow(self, self.options)
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 1025, in NewPithosWindow
    window.finish_initializing(builder, options)
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 176, in finish_initializing
    load_plugins(self)
  File "/usr/lib/python3.4/site-packages/pithos/plugin.py", line 94, in load_plugins
    plugin.enable()
  File "/usr/lib/python3.4/site-packages/pithos/plugin.py", line 36, in enable
    self.on_enable()
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 46, in on_enable
    self.connect(self.window.preferences['lastfm_key'])
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 59, in connect
    self.network = pylast.get_lastfm_network(
NameError: name 'pylast' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 1103, in prefs_cb
    self.window.show_preferences()
AttributeError: 'NoneType' object has no attribute 'show_preferences'

**Comment by TingPing** [comment]
@skamansam Your issue sounds unrelated, but I just pushed a fix for it to rpmfusion (will take a while for you to get it).
