### ISSUE TITLE
gi._glib.GError: Unknown internal child: plus_button

### ISSUE THREAD

**Issue by stevenvergenz** [pithos/pithos#165]
Perhaps this is just a dependency error or something, but I cannot find any information on it whatsoever on the internet, largely due to the fact that one cannot google "gi" and get anything useful. I'm on Fedora 19 x86_64, and when I try to launch pithos installed from source (098f7e1500cc56855c7427b2eb877a33c6fb6aa6) I get the following error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/pithos-1.0.1-py3.3.egg/pithos/pithos.py", line 1126, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.3/site-packages/pithos-1.0.1-py3.3.egg/pithos/pithos.py", line 1133, in do_activate
    self.window = NewPithosWindow(self, self.options)
  File "/usr/lib/python3.3/site-packages/pithos-1.0.1-py3.3.egg/pithos/pithos.py", line 1064, in NewPithosWindow
    builder.add_from_file(get_ui_file('main'))
  File "/usr/lib64/python3.3/site-packages/gi/types.py", line 113, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unknown internal child: plus_button
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/pithos-1.0.1-py3.3.egg/pithos/pithos.py", line 1139, in do_shutdown
    self.window.destroy()
AttributeError: 'NoneType' object has no attribute 'destroy'
[svergenz@localhost ~]$ 
```

**Comment by TingPing** [comment]
Fedora 19 is too old to use Pithos 1.0.x. This was due to a change in Glade that broke backwards compat...
