### ISSUE TITLE
When running as module: GLib.Error: g-resource-error-quark: The resource at '/io/github/Pithos/ui/AboutPithosDialog.ui' does not exist (0)

### ISSUE THREAD

**Issue by xenoxaos** [pithos/pithos#252]
I have Pithos installed as a package and it works fine, however if run as a module I get the following error:

[xenoxaos@tellurium ~]$ git clone git@github.com:pithos/pithos.git
Cloning into 'pithos'...
remote: Counting objects: 3197, done.
remote: Total 3197 (delta 0), reused 0 (delta 0), pack-reused 3197
Receiving objects: 100% (3197/3197), 1.28 MiB | 96.00 KiB/s, done.
Resolving deltas: 100% (1975/1975), done.
Checking connectivity... done.
[xenoxaos@tellurium ~]$ cd pithos/
[xenoxaos@tellurium pithos]$ python3 -m pithos
Traceback (most recent call last):
  File "/home/xenoxaos/pithos/pithos/gi_composites.py", line 232, in __call__
    template_bytes = Gio.resources_lookup_data(self.ui, Gio.ResourceLookupFlags.NONE)
GLib.Error: g-resource-error-quark: The resource at '/io/github/Pithos/ui/AboutPithosDialog.ui' does not exist (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xenoxaos/pithos/pithos/__main__.py", line 1, in <module>
    from pithos.application import main
  File "/home/xenoxaos/pithos/pithos/application.py", line 26, in <module>
    from .pithos import PithosWindow
  File "/home/xenoxaos/pithos/pithos/pithos.py", line 40, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/home/xenoxaos/pithos/pithos/AboutPithosDialog.py", line 23, in <module>
    class AboutPithosDialog(Gtk.AboutDialog):
  File "/home/xenoxaos/pithos/pithos/gi_composites.py", line 241, in __call__
    with open(ui, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/io/github/Pithos/ui/AboutPithosDialog.ui'
[xenoxaos@tellurium pithos]$ 

If this is a PEBKAC, please let me know!

**Comment by TingPing** [comment]
See #239
