### ISSUE TITLE
Updated to 1.6.2 gstreamer (including python gst) and now can't launch

### ISSUE THREAD

**Issue by Justinzobel** [pithos/pithos#258]
```
pithos
Traceback (most recent call last):
  File "/usr/bin/pithos", line 9, in <module>
    load_entry_point('pithos==1.1.2', 'gui_scripts', 'pithos')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 35, in <module>
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3.4/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
```

**Comment by TingPing** [comment]
Works fine here on 1.6.2 (archlinux).

**Comment by Justinzobel** [comment]
Any idea on what might be causing the error then?

**Comment by TingPing** [comment]
Maybe something got corrupted? Try reinstalling the `gstreamer` package.

**Comment by Justinzobel** [comment]
Re-installed all of gstreamer 1.6.2 packages and still same error.

**Comment by TingPing** [comment]
Just to verify running `python3 -c 'from gi.repository import Gst'` produces the same error right? If so this just doesn't have anything to do with Pithos and you are probably better off finding support from your distro.

**Comment by Justinzobel** [comment]
Sorted, needed to add gobject-introspection as it was removed from the Solus base image. Thanks for your help @TingPing
