### ISSUE TITLE
Pithos stops working after upgrading to Kubuntu 16.04

### ISSUE THREAD

**Issue by riftware** [pithos/pithos#296]
I have a previously working Pithos install that stopped working after I upgraded from 15.10 to 16.04 Kubuntu   (should be basically the same as ubuntu just with KDE)

I get the following error:
```python
~$ pithos
Traceback (most recent call last):
  File "/usr/local/bin/pithos", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pithos==1.1.2' distribution was not found and is required by the application
```

**Comment by TingPing** [comment]
Just try reinstalling it? I mean when you change an entire system under a local install things might go wrong...

**Comment by riftware** [comment]
The problem is apparently the PPA doesn't exist for this version of
ubuntu/kubuntu yet - I tried uninstalling and then went to install and
found that out.

**Comment by Ironlenny** [comment]
Who's managing the PPA?

**Comment by TingPing** [comment]
Seems like nobody at this point. See #259
