### ISSUE TITLE
Latest 1.2.0 ppa build for Ubuntu is missing a dependency

### ISSUE THREAD

**Issue by RyanNerd** [pithos/pithos#321]
See the error message below. This fixes the issue:

`sudo apt-get install gir1.2-secret-1`

Error dump:
Traceback (most recent call last):
  File "/usr/bin/pithos", line 43, in <module>
    from pithos import application
  File "/usr/lib/python3.5/site-packages/pithos/application.py", line 26, in <module>
    from .pithos import PithosWindow
  File "/usr/lib/python3.5/site-packages/pithos/pithos.py", line 41, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/lib/python3.5/site-packages/pithos/PreferencesPithosDialog.py", line 22, in <module>
    from .util import get_account_password, set_account_password
  File "/usr/lib/python3.5/site-packages/pithos/util.py", line 21, in <module>
    gi.require_version('Secret', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available

**Comment by TingPing** [comment]
Fixed.

**Comment by Organic-Marble** [comment]
Not fixed in the 14.04 repos as of 7/30/2016.  Fixed in the 16.04 repos.
