### ISSUE TITLE
GLib.Error: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login

### ISSUE THREAD

**Issue by astronouth7303** [pithos/pithos#336]
```console
$ pithos
** Message: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/application.py", line 101, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.5/site-packages/pithos/application.py", line 107, in do_activate
    maybe_migrate_settings()
  File "/usr/lib/python3.5/site-packages/pithos/migrate_settings.py", line 85, in maybe_migrate_settings
    set_account_password(prefs['username'], val)
  File "/usr/lib/python3.5/site-packages/pithos/util.py", line 52, in set_account_password
    "Pandora Account", password, None)
GLib.Error: g-dbus-error-quark: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login (19)
$ pithos --version
Pithos 1.2.1
$ gnome-keyring-daemon --version
gnome-keyring-daemon: 3.20.0
testing: enabled
```

D-Feet reports that `gnome-keyring-daemon` is running, but does not have an object at path `/org/freedesktop/secrets/collection/login`.

**Comment by TingPing** [comment]
Hmm, same version here and it has it.

**Comment by astronouth7303** [comment]
I do have the object path `/org/freedesktop/secrets/collection/session`, though.

**Comment by astronouth7303** [comment]
Huh, so after a reboot, Pithos created a new keyring, and then happily started again.

I'm going to chalk this up to some kind of irreproducable weird interaction between i3, systemd, and gnome-keyring.
