### ISSUE TITLE
Errors when enabling MPRIS plugin on Raspbian(Raspberry Pi2)

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#343]
While debugging for another issue on the Raspberry Pi2 I ran into this when the MPRIS plugin was enabled:

``` bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pithos/PreferencesPithosDialog.py", line 66, in on_activated
    self.plugin.enable()
  File "/usr/local/lib/python3.4/site-packages/pithos/plugin.py", line 40, in enable
    self.on_enable()
  File "/usr/local/lib/python3.4/site-packages/pithos/plugins/mpris.py", line 41, in on_enable
    self.service = self.PithosDBusProxy(self.window, connection=self.bus)
  File "/usr/local/lib/python3.4/site-packages/pithos/plugins/_dbus_service.py", line 27, in __init__
    super().__init__(object_path=DBUS_OBJECT_PATH, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pithos/plugins/dbus_util/DBusServiceObject.py", line 272, in __init__
    self.__dbus_export()
  File "/usr/local/lib/python3.4/site-packages/pithos/plugins/dbus_util/DBusServiceObject.py", line 304, in __dbus_export
    self.__dbus_set_property
TypeError: argument vtable: Expected Gio.DBusInterfaceVTable, but got pithos.plugins.dbus_util.DBusServiceObject.method
```

It's not a huge deal on the Pi since it doesn't have a MPRIS client by default anyway. Just thought I'd report it.

**Comment by TingPing** [comment]
What is the output of this: ```python3 -c 'from gi.repository import Gio; help(Gio.DBusConnection)' | grep register_object```

**Comment by JasonLG1979** [comment]
```bash
 |  register_object = gi.FunctionInfo(register_object)
 |      register_object(self, object_path:str, interface_info:Gio.DBusInterfaceInfo, vtable:Gio.DBusInterfaceVTable=None, user_data=None, user_data_free_func:GLib.DestroyNotify) -> int
 |  unregister_object = gi.FunctionInfo(unregister_object)
 |      unregister_object(self, registration_id:int) -> bool
```

**Comment by TingPing** [comment]
So the current API is:

```python
 register_object(self, object_path:str, interface_info:Gio.DBusInterfaceInfo, method_call_closure:GObject.Closure=None, get_property_closure:GObject.Closure=None, set_property_closure:GObject.Closure=None) -> int
```

So we just need to find out what version of pygobject changed this and make that our minimum requirement.

**Comment by JasonLG1979** [comment]
> So we just need to find out what version of pygobject changed this and make that our minimum requirement (for that plugin).

"Just" Lol!!! Gotta love an unstable API,lol!!!

**Comment by TingPing** [comment]
Yea, thats what happens when you generate an api off of another api in another language.

**Comment by JasonLG1979** [comment]
That's what happens when you develop GNOME apps,lol!!!

**Comment by TingPing** [comment]
Language bindings are far more problematic than the actual libraries.

**Comment by JasonLG1979** [comment]
I wouldn't know. I just know that GNOME is famous for breaking their API,lol!!!
