### ISSUE TITLE
Pithos fails to start correctly

### ISSUE THREAD

**Issue by codingcoug** [pithos/pithos#376]
After opening pithos you can see that it logs in in the bottom left hand corner and then tries to load the songs but somewhere along the way it's failing. 

I'm using pithos version 1.2.1 

here's the terminal readout

```python
ERROR - gobject_worker:_default_errorback:47 - Unhandled exception in worker thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/gobject_worker.py", line 34, in _run
    result = command(*args)
  File "/usr/lib/python3.5/site-packages/pithos/pithos.py", line 642, in get_album_art
    image = f.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

ERROR - gobject_worker:_default_errorback:47 - Unhandled exception in worker thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/gobject_worker.py", line 34, in _run
    result = command(*args)
  File "/usr/lib/python3.5/site-packages/pithos/pithos.py", line 642, in get_album_art
    image = f.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

if it helps the album art on the first song does not show up but the songs that would play next display fine.

**Comment by TingPing** [comment]
We can better handle that error so it doesn't print but the failure in the first place is external to Pithos.

**Comment by codingcoug** [comment]
after further playing around it seems to be more VM related. I added a bridged connection and it loaded just fine.

**Comment by JasonLG1979** [comment]
Closed because it's invalid. Improperly configured VM.
