### ISSUE TITLE
Stacktraces dumped after socket timeout

### ISSUE THREAD

**Issue by stevekuznetsov** [pithos/pithos#413]
When re-connecting after an invalid auth token, I still see Pithos fail to reconnect and re-try by itself. Today I also noticed in the log there are stacktraces being pumped out:

```
Jan 30 13:31:13 io.github.Pithos[3980]: Manual retry
Jan 30 13:31:13 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:31:17 io.github.Pithos[3980]: fault code: 1001 message: An unexpected error occurred
Jan 30 13:31:17 io.github.Pithos[3980]: Automatic reconnect after invalid auth token
Jan 30 13:31:19 io.github.Pithos[3980]: Time offset is 0.7843074798583984
Jan 30 13:31:44 io.github.Pithos[3980]: Traceback (most recent call last):
                                          File "/usr/local/lib/python3.4/site-packages/pithos/gobject_worker.py", line 30, in run
                                            result = command(*args)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 331, in get_playlist
                                            }, https=True)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 126, in json_call
                                            with self.opener.open(req, timeout=HTTP_TIMEOUT) as response:
                                          File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
                                            response = self._open(req, data)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
                                            '_open', req)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
                                            result = func(*args)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1297, in https_open
                                            context=self._context, check_hostname=self._check_hostname)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1257, in do_open
                                            r = h.getresponse()
                                          File "/usr/lib64/python3.5/http/client.py", line 1197, in getresponse
                                            response.begin()
                                          File "/usr/lib64/python3.5/http/client.py", line 297, in begin
                                            version, status, reason = self._read_status()
                                          File "/usr/lib64/python3.5/http/client.py", line 258, in _read_status
                                            line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                          File "/usr/lib64/python3.5/socket.py", line 575, in readinto
                                            return self._sock.recv_into(b)
                                          File "/usr/lib64/python3.5/ssl.py", line 929, in recv_into
                                            return self.read(nbytes, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 791, in read
                                            return self._sslobj.read(len, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 575, in read
                                            v = self._sslobj.read(len, buffer)
                                        socket.timeout: The read operation timed out
Jan 30 13:31:44 io.github.Pithos[3980]: Traceback (most recent call last):
                                          File "/usr/local/lib/python3.4/site-packages/pithos/gobject_worker.py", line 30, in run
                                            result = command(*args)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 331, in get_playlist
                                            }, https=True)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 126, in json_call
                                            with self.opener.open(req, timeout=HTTP_TIMEOUT) as response:
                                          File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
                                            response = self._open(req, data)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
                                            '_open', req)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
                                            result = func(*args)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1297, in https_open
                                            context=self._context, check_hostname=self._check_hostname)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1257, in do_open
                                            r = h.getresponse()
                                          File "/usr/lib64/python3.5/http/client.py", line 1197, in getresponse
                                            response.begin()
                                          File "/usr/lib64/python3.5/http/client.py", line 297, in begin
                                            version, status, reason = self._read_status()
                                          File "/usr/lib64/python3.5/http/client.py", line 258, in _read_status
                                            line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                          File "/usr/lib64/python3.5/socket.py", line 575, in readinto
                                            return self._sock.recv_into(b)
                                          File "/usr/lib64/python3.5/ssl.py", line 929, in recv_into
                                            return self.read(nbytes, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 791, in read
                                            return self._sslobj.read(len, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 575, in read
                                            v = self._sslobj.read(len, buffer)
                                        socket.timeout: The read operation timed out
Jan 30 13:31:49 io.github.Pithos[3980]: Traceback (most recent call last):
                                          File "/usr/local/lib/python3.4/site-packages/pithos/gobject_worker.py", line 30, in run
                                            result = command(*args)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 230, in connect
                                            user = self.json_call('auth.userLogin', {'username': user, 'password': password, 'loginType': 'user'}, https=True)
                                          File "/usr/local/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 126, in json_call
                                            with self.opener.open(req, timeout=HTTP_TIMEOUT) as response:
                                          File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
                                            response = self._open(req, data)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
                                            '_open', req)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
                                            result = func(*args)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1297, in https_open
                                            context=self._context, check_hostname=self._check_hostname)
                                          File "/usr/lib64/python3.5/urllib/request.py", line 1257, in do_open
                                            r = h.getresponse()
                                          File "/usr/lib64/python3.5/http/client.py", line 1197, in getresponse
                                            response.begin()
                                          File "/usr/lib64/python3.5/http/client.py", line 297, in begin
                                            version, status, reason = self._read_status()
                                          File "/usr/lib64/python3.5/http/client.py", line 258, in _read_status
                                            line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                          File "/usr/lib64/python3.5/socket.py", line 575, in readinto
                                            return self._sock.recv_into(b)
                                          File "/usr/lib64/python3.5/ssl.py", line 929, in recv_into
                                            return self.read(nbytes, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 791, in read
                                            return self._sslobj.read(len, buffer)
                                          File "/usr/lib64/python3.5/ssl.py", line 575, in read
                                            v = self._sslobj.read(len, buffer)
                                        socket.timeout: The read operation timed out
```

**Comment by stevekuznetsov** [comment]
Now I'm seeing
```
Jan 30 13:47:04 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:05 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 13:47:06 io.github.Pithos[3980]: Manual retry
Jan 30 13:47:06 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:07 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 13:47:08 io.github.Pithos[3980]: Manual retry
Jan 30 13:47:08 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:09 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 13:47:09 io.github.Pithos[3980]: Manual retry
Jan 30 13:47:09 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:10 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 13:47:11 io.github.Pithos[3980]: Manual retry
Jan 30 13:47:11 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:11 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 13:47:12 io.github.Pithos[3980]: Manual retry
Jan 30 13:47:12 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 13:47:12 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
```

**Comment by JasonLG1979** [comment]
Pandora was down there for a bit.

**Comment by stevekuznetsov** [comment]
I expect Pithos to work around the Pandora servers being down 🤣 

Should we just close this, then?

**Comment by JasonLG1979** [comment]
I'd say so. It's up again for me at least.

**Comment by stevekuznetsov** [comment]
Hmm.... unfortunately not the case for me:
```
-- Logs begin at Wed 2016-12-14 13:01:19 EST, end at Mon 2017-01-30 14:51:11 EST. --
Jan 30 14:50:56 io.github.Pithos[3980]: Selecting station 3172841149648029983; total = 49
Jan 30 14:50:56 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 14:50:57 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 14:50:58 io.github.Pithos[3980]: Manual retry
Jan 30 14:50:58 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 14:50:59 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 14:50:59 io.github.Pithos[3980]: Manual retry
Jan 30 14:50:59 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 14:51:00 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
Jan 30 14:51:01 io.github.Pithos[3980]: Manual retry
Jan 30 14:51:01 io.github.Pithos[3980]: pandora: Get Playlist
Jan 30 14:51:01 io.github.Pithos[3980]: fault code: 9 message: An unexpected error occurred
```

I asked this on IRC but yet no reply -- how can I get `pithos --debug` output to the system journal? I edited the `.desktop` file's `Exec` statement to be `pithos --debug` and I'm launching using the GNOME desktop shortcuts but I don't see anything other than the normal output in the journal.

**Comment by JasonLG1979** [comment]
I'm pretty sure you can change:
https://github.com/pithos/pithos/blob/master/pithos/application.py#L102

to:
```python
journal.setLevel(logging.DEBUG)
```

**Comment by JasonLG1979** [comment]
We might want to have a setting in the advanced setting for changing the log level.

**Comment by JasonLG1979** [comment]
Here you go @stevekuznetsov this makes journald logging a plugin and totally independent of the stream logging. You can enable, disable and set the logging level at run time.

 https://github.com/pithos/pithos/pull/415

**Comment by JasonLG1979** [comment]
Like all plugins the user has to enable it. Otherwise it doesn't log to the journal.

**Comment by JasonLG1979** [comment]
@stevekuznetsov I'm going to close this because Pandora being down isn't a bug,lol!!! But it did get the ball rolling for the Logging Plugin so thanks for that.
