### ISSUE TITLE
name _current_collection is assigned before global declaration

### ISSUE THREAD

**Issue by Stebalien** [pithos/pithos#439]
On Arch Linux, pithos 1.3, I'm getting the following error on start:

```rust
Traceback (most recent call last):
  File "/usr/bin/pithos", line 41, in <module>
    from pithos import application
  File "/usr/lib/python3.6/site-packages/pithos/application.py", line 24, in <module>
    from .pithos import PithosWindow
  File "/usr/lib/python3.6/site-packages/pithos/pithos.py", line 40, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/lib/python3.6/site-packages/pithos/PreferencesPithosDialog.py", line 21, in <module>
    from .util import get_account_password, set_account_password
  File "/usr/lib/python3.6/site-packages/pithos/util.py", line 66
    global _current_collection
SyntaxError: name '_current_collection' is assigned to before global declaration
```

**Comment by TingPing** [comment]
This seems to be a Python 3.6 only exception btw.

**Comment by JasonLG1979** [comment]
> For any readers this seems to be a Python 3.6 only exception btw.

I was wondering...

**Comment by JasonLG1979** [comment]
Add that to 1.3.1 I guess. I'm sure there will be more,lol!!!

**Comment by JasonLG1979** [comment]
We could easily make the libsecret stuff a proper class to avoid the global?

**Comment by Stebalien** [comment]
Thanks!

**Comment by JasonLG1979** [comment]
@Stebalien looking at your AUR. libnotify is no longer a dependency.
